name: Larastan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  larastan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Static analysis (Larastan)
      run: vendor/bin/phpstan analyse --no-progress
